### ISSUE TITLE
Crash by Import

### ISSUE THREAD

**Issue by HauDichT** [MichaeINeumann/IF-PanelCreator#1]
![grafik](https://user-images.githubusercontent.com/56257666/142836432-4c766d81-9103-4290-923f-63f20ba1b828.png)

Servus Michael,

schau dir wenn du zeit hast mal das Importieren einer bestehenden File an.
Da kommt es zum Crash wenn ich versuche diese zu Importieren.

Das wäre mega wenn dies funktionieren würde, kannst dir ein Kaffee dafür bei mir abholen :)

Hier ein IF-Panel von einem bestehenden Projekt das auf der Steuerung funktioniert.
[IFPANEL.zip](https://github.com/MichaeINeumann/IF-PanelCreator/files/7579748/IFPANEL.zip)

Gruß Sebastian

**Comment by MichaeINeumann** [comment]
Hallo Sebastian,
bitte speichere die Datei in der Codierung UTF-8(mit BOM).
In UltraEdit direkt neben dem Speichern Knopf.

Please save the file in UTF-8 format.
